/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author julxo
 */
public class PedirServicio extends javax.swing.JFrame {

    /**
     * Creates new form PedirServicio
     */
    public PedirServicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtvalorserv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtvalorcat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbcat = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbmediopago = new javax.swing.JComboBox<>();
        btnpedirserv = new javax.swing.JButton();
        cmbtiposervadd = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedir Servicio");

        jLabel1.setText("Tipo de servicio");

        jLabel2.setText("Valor de Servicio");

        txtvalorserv.setEditable(false);

        jLabel3.setText("Valor de Categoría");

        txtvalorcat.setEditable(false);

        jLabel4.setText("Categoria");

        cmbcat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Especial", "Urgente" }));
        cmbcat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbcatItemStateChanged(evt);
            }
        });

        jLabel6.setText("Medio de pago");

        cmbmediopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));

        btnpedirserv.setText("Pedir Servicio");

        cmbtiposervadd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbtiposervaddItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbcat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbmediopago, 0, 100, Short.MAX_VALUE)
                            .addComponent(cmbtiposervadd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvalorcat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvalorserv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btnpedirserv)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtvalorserv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbtiposervadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtvalorcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmbcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbmediopago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnpedirserv)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbtiposervaddItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbtiposervaddItemStateChanged
        if (cmbtiposervadd.getSelectedItem().equals("Pasajeros")) {
            txtvalorserv.setText("100000");
        }
        if (cmbtiposervadd.getSelectedItem().equals("Alimentos")) {
            txtvalorserv.setText("150000");
        }
    }//GEN-LAST:event_cmbtiposervaddItemStateChanged

    private void cmbcatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbcatItemStateChanged
        if (cmbcat.getSelectedItem().equals("Normal")) {
            txtvalorcat.setText("1000");
        }
        if (cmbcat.getSelectedItem().equals("Especial")) {
            txtvalorcat.setText("5000");
        }
        if (cmbcat.getSelectedItem().equals("Urgente")) {
            txtvalorcat.setText("15000");
        }
    }//GEN-LAST:event_cmbcatItemStateChanged

    public JComboBox<String> getCmbtiposervadd() {
        return cmbtiposervadd;
    }

    public void setCmbtiposervadd(JComboBox<String> cmbtiposervadd) {
        this.cmbtiposervadd = cmbtiposervadd;
    }

    public JButton getBtnpedirserv() {
        return btnpedirserv;
    }

    public void setBtnpedirserv(JButton btnpedirserv) {
        this.btnpedirserv = btnpedirserv;
    }

    public JComboBox<String> getCmbcat() {
        return cmbcat;
    }

    public void setCmbcat(JComboBox<String> cmbcat) {
        this.cmbcat = cmbcat;
    }

    public JComboBox<String> getCmbmediopago() {
        return cmbmediopago;
    }

    public void setCmbmediopago(JComboBox<String> cmbmediopago) {
        this.cmbmediopago = cmbmediopago;
    }

    public JTextField getTxtvalorcat() {
        return txtvalorcat;
    }

    public void setTxtvalorcat(JTextField txtvalorcat) {
        this.txtvalorcat = txtvalorcat;
    }

    public JTextField getTxtvalorserv() {
        return txtvalorserv;
    }

    public void setTxtvalorserv(JTextField txtvalorserv) {
        this.txtvalorserv = txtvalorserv;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpedirserv;
    private javax.swing.JComboBox<String> cmbcat;
    private javax.swing.JComboBox<String> cmbmediopago;
    private javax.swing.JComboBox<String> cmbtiposervadd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtvalorcat;
    private javax.swing.JTextField txtvalorserv;
    // End of variables declaration//GEN-END:variables
}
