/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author julxo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel1 = new javax.swing.JPanel();
        lbltitulotabla = new javax.swing.JLabel();
        lblbienvenido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbltitulopedir = new javax.swing.JLabel();
        btndisponibilidad = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblultserv = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablageneral = new javax.swing.JTable();
        scrollultsev = new javax.swing.JScrollPane();
        tblultserv = new javax.swing.JTable();
        btnterminarserv = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        btnregistroadm = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaclientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaconducts = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btndelcliente = new javax.swing.JButton();
        btnactcliente = new javax.swing.JButton();
        btnactcond = new javax.swing.JButton();
        btndelcond = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        panel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnvalt_servs = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblvalt_servs = new javax.swing.JTable();
        btn_cantservs_mes = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblcantservs = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblservs_clientes = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btn_servs_clientes = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblvalt_mediopago = new javax.swing.JTable();
        btnvalt_mediopago = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        date1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        date2 = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmusuario = new javax.swing.JMenu();
        jmifoto = new javax.swing.JMenuItem();
        jminombre = new javax.swing.JMenuItem();
        jmiuser = new javax.swing.JMenuItem();
        jmisesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltitulotabla.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbltitulotabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulotabla.setText("TOTAL DE SERVICIOS REALIZADOS");
        panel1.add(lbltitulotabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 144, 1168, 40));

        lblbienvenido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblbienvenido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblbienvenido.setText("Bienvenid@ usuario");
        panel1.add(lblbienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 92, 1201, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Aventureros S.A.");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1213, 67));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 1213, 10));

        lbltitulopedir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbltitulopedir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulopedir.setText("PEDIR SERVICIO");
        panel1.add(lbltitulopedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 575, -1, 40));

        btndisponibilidad.setText("Consultar Disponibilidad");
        panel1.add(btndisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 621, -1, -1));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 559, 1145, 10));

        lblultserv.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblultserv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblultserv.setText("ÚLTIMO SERVICIO PEDIDO");
        panel1.add(lblultserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 575, 870, 40));

        tablageneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablageneral);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 249, 1145, 304));

        tblultserv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        scrollultsev.setViewportView(tblultserv);

        panel1.add(scrollultsev, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 621, 868, 50));

        btnterminarserv.setText("Terminar");
        panel1.add(btnterminarserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(1092, 589, -1, -1));

        jTabbedPane1.addTab("Principal", panel1);

        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnregistroadm.setText("Registrar Nuevo Usuario");
        panel2.add(btnregistroadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        tablaclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaclientes);

        panel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 152, 560, 410));

        tablaconducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaconducts);

        panel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 152, 560, 410));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Conductores");
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 560, 28));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INFORMACIÓN USUARIOS DE AVENTUREROS S.A.");
        panel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 6, 1150, 55));

        btndelcliente.setText("Eliminar");
        panel2.add(btndelcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 574, -1, -1));

        btnactcliente.setText("Actualizar");
        panel2.add(btnactcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 574, -1, -1));

        btnactcond.setText("Actualizar");
        panel2.add(btnactcond, new org.netbeans.lib.awtextra.AbsoluteConstraints(1095, 574, -1, -1));

        btndelcond.setText("Eliminar");
        panel2.add(btndelcond, new org.netbeans.lib.awtextra.AbsoluteConstraints(1004, 574, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Clientes");
        panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 560, 28));
        panel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1210, 10));

        jTabbedPane1.addTab("Usuarios", panel2);

        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VALOR TOTAL DE LOS SERVICIOS REALIZADOS");
        panel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 550, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INFORMACIÓN SOBRE SERVICIOS REALIZADOS");
        panel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 6, 1150, 55));

        btnvalt_servs.setText("Consultar");
        panel3.add(btnvalt_servs, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        tblvalt_servs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblvalt_servs);

        panel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 146, 550, 203));

        btn_cantservs_mes.setText("Consultar");
        panel3.add(btn_cantservs_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, -1, -1));

        tblcantservs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tblcantservs);

        panel3.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 146, 520, 203));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CANTIDAD DE SERVICIOS REALIZADOS AL MES");
        panel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 520, -1));

        tblservs_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblservs_clientes);

        panel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 550, 203));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CLIENTES QUE HAN SOLICITADO SERVICIOS");
        panel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 550, -1));

        btn_servs_clientes.setText("Consultar");
        panel3.add(btn_servs_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("VALOR TOTAL DE SERVICIOS POR SU MEDIO DE PAGO");
        panel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 520, -1));

        tblvalt_mediopago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tblvalt_mediopago);

        panel3.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 450, 520, 203));

        btnvalt_mediopago.setText("Consultar");
        panel3.add(btnvalt_mediopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, -1, -1));
        panel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1210, 10));

        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setDateFormatString("y-MM-d");
        panel3.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 120, -1));

        jLabel10.setText("Primer fecha: ");
        panel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, 20));

        jLabel12.setText("Segunda fecha:");
        panel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, 20));

        date2.setForeground(new java.awt.Color(255, 255, 255));
        date2.setDateFormatString("y-MM-d");
        panel3.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 120, -1));

        jTabbedPane1.addTab("Consultas", panel3);

        jDesktopPane1.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jMenuBar1.setOpaque(true);

        jMenu2.setText("                                                                                                                                                                                                                                                                                                                                                                                                                      ");
        jMenu2.setEnabled(false);
        jMenuBar1.add(jMenu2);

        jmusuario.setText("Usuario");

        jmifoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmusuario.add(jmifoto);

        jminombre.setText("nombre");
        jminombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmusuario.add(jminombre);

        jmiuser.setText("usuario");
        jmiuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmusuario.add(jmiuser);

        jmisesion.setText("Cerrar Sesión");
        jmisesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmusuario.add(jmisesion);

        jMenuBar1.add(jmusuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JScrollPane getScrollultsev() {
        return scrollultsev;
    }

    public void setScrollultsev(JScrollPane scrollultsev) {
        this.scrollultsev = scrollultsev;
    }

    
    public JButton getBtn_cantservs_mes() {
        return btn_cantservs_mes;
    }

    public void setBtn_cantservs_mes(JButton btn_cantservs_mes) {
        this.btn_cantservs_mes = btn_cantservs_mes;
    }

    public JButton getBtn_servs_clientes() {
        return btn_servs_clientes;
    }

    public void setBtn_servs_clientes(JButton btn_servs_clientes) {
        this.btn_servs_clientes = btn_servs_clientes;
    }

    public JButton getBtnvalt_servs() {
        return btnvalt_servs;
    }

    public void setBtnval_t_servs(JButton btnvalt_servs) {
        this.btnvalt_servs = btnvalt_servs;
    }

    public JButton getBtnvalt_mediopago() {
        return btnvalt_mediopago;
    }

    public void setBtnvalt_mediopago(JButton btnvalt_mediopago) {
        this.btnvalt_mediopago = btnvalt_mediopago;
    }

    public JTable getTblcantservs() {
        return tblcantservs;
    }

    public void setTblcantservs(JTable tblcantservs) {
        this.tblcantservs = tblcantservs;
    }

    public JTable getTblservs_clientes() {
        return tblservs_clientes;
    }

    public void setTblservs_clientes(JTable tblservs_clientes) {
        this.tblservs_clientes = tblservs_clientes;
    }

    public JTable getTblvalt_mediopago() {
        return tblvalt_mediopago;
    }

    public void setTblvalt_mediopago(JTable tblvalt_mediopago) {
        this.tblvalt_mediopago = tblvalt_mediopago;
    }

    public JTable getTblvalt_servs() {
        return tblvalt_servs;
    }

    public void setTblvalt_servs(JTable tblvalt_servs) {
        this.tblvalt_servs = tblvalt_servs;
    }

    
    public JDateChooser getDate1() {
        return date1;
    }

    public void setDate1(JDateChooser date1) {
        this.date1 = date1;
    }

    public JDateChooser getDate2() {
        return date2;
    }

    public void setDate2(JDateChooser date2) {
        this.date2 = date2;
    }

    
    public JMenuItem getJminombre() {
        return jminombre;
    }

    public void setJminombre(JMenuItem jminombre) {
        this.jminombre = jminombre;
    }

    
    public JButton getBtnterminarserv() {
        return btnterminarserv;
    }

    public void setBtnterminarserv(JButton btnterminarserv) {
        this.btnterminarserv = btnterminarserv;
    }

    
    public JTable getTblultserv() {
        return tblultserv;
    }

    public void setTblultserv(JTable tblultserv) {
        this.tblultserv = tblultserv;
    }

    public JLabel getLblultserv() {
        return lblultserv;
    }

    public void setLblultserv(JLabel lblultserv) {
        this.lblultserv = lblultserv;
    }

    

    
    public JButton getBtnactcliente() {
        return btnactcliente;
    }

    public void setBtnactcliente(JButton btnactcliente) {
        this.btnactcliente = btnactcliente;
    }

    public JButton getBtnactcond() {
        return btnactcond;
    }

    public void setBtnactcond(JButton btnactcond) {
        this.btnactcond = btnactcond;
    }

    public JButton getBtndelcliente() {
        return btndelcliente;
    }

    public void setBtndelcliente(JButton btndelcliente) {
        this.btndelcliente = btndelcliente;
    }

    public JButton getBtndelcond() {
        return btndelcond;
    }

    public void setBtndelcond(JButton btndelcond) {
        this.btndelcond = btndelcond;
    }

    public JTable getTablaclientes() {
        return tablaclientes;
    }

    public void setTablaclientes(JTable tablaclientes) {
        this.tablaclientes = tablaclientes;
    }

    public JTable getTablaconducts() {
        return tablaconducts;
    }

    public void setTablaconducts(JTable tablaconducts) {
        this.tablaconducts = tablaconducts;
    }

    

    
    public JButton getBtnregistroadm() {
        return btnregistroadm;
    }

    /**
     * @param args the command line arguments
     */
    public void setBtnregistroadm(JButton btnregistroadm) {
        this.btnregistroadm = btnregistroadm;
    }

    public JButton getBtndisponibilidad() {
        return btndisponibilidad;
    }

    public void setBtndisponibilidad(JButton btndisponibilidad) {
        this.btndisponibilidad = btndisponibilidad;
    }

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
        this.jDesktopPane1 = jDesktopPane1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getJmifoto() {
        return jmifoto;
    }

    public void setJmifoto(JMenuItem jmifoto) {
        this.jmifoto = jmifoto;
    }

    public JMenuItem getJmisesion() {
        return jmisesion;
    }

    public void setJmisesion(JMenuItem jmisesion) {
        this.jmisesion = jmisesion;
    }

    public JMenuItem getJmiuser() {
        return jmiuser;
    }

    public void setJmiuser(JMenuItem jmiuser) {
        this.jmiuser = jmiuser;
    }

    

    public void setjMenuItem2(JMenuItem jMenuItem2) {
        this.jmiuser = jMenuItem2;
    }

    public JMenuItem getjMenuItem3() {
        return jmisesion;
    }

    public void setjMenuItem3(JMenuItem jMenuItem3) {
        this.jmisesion = jMenuItem3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }


    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public void setjSeparator2(JSeparator jSeparator2) {
        this.jSeparator2 = jSeparator2;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JMenu getJmusuario() {
        return jmusuario;
    }

    public void setJmusuario(JMenu jmusuario) {
        this.jmusuario = jmusuario;
    }

    public JLabel getLblbienvenido() {
        return lblbienvenido;
    }

    public void setLblbienvenido(JLabel lblbienvenido) {
        this.lblbienvenido = lblbienvenido;
    }


    

    public JLabel getLbltitulopedir() {
        return lbltitulopedir;
    }

    public void setLbltitulopedir(JLabel lbltitulopedir) {
        this.lbltitulopedir = lbltitulopedir;
    }

    public JLabel getLbltitulotabla() {
        return lbltitulotabla;
    }

    public void setLbltitulotabla(JLabel lbltitulotabla) {
        this.lbltitulotabla = lbltitulotabla;
    }

    public JPanel getPanel1() {
        return panel1;
    }

    public void setPanel1(JPanel panel1) {
        this.panel1 = panel1;
    }

    public JPanel getPanel2() {
        return panel2;
    }

    public void setPanel2(JPanel panel2) {
        this.panel2 = panel2;
    }

    public JPanel getPanel3() {
        return panel3;
    }

    public void setPanel3(JPanel panel3) {
        this.panel3 = panel3;
    }

    public JTable getTablageneral() {
        return tablageneral;
    }

    /**
     * @param args the command line arguments
     */
    public void setTablageneral(JTable tablageneral) {
        this.tablageneral = tablageneral;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cantservs_mes;
    private javax.swing.JButton btn_servs_clientes;
    private javax.swing.JButton btnactcliente;
    private javax.swing.JButton btnactcond;
    private javax.swing.JButton btndelcliente;
    private javax.swing.JButton btndelcond;
    private javax.swing.JButton btndisponibilidad;
    private javax.swing.JButton btnregistroadm;
    private javax.swing.JButton btnterminarserv;
    private javax.swing.JButton btnvalt_mediopago;
    private javax.swing.JButton btnvalt_servs;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem jmifoto;
    private javax.swing.JMenuItem jminombre;
    private javax.swing.JMenuItem jmisesion;
    private javax.swing.JMenuItem jmiuser;
    private javax.swing.JMenu jmusuario;
    private javax.swing.JLabel lblbienvenido;
    private javax.swing.JLabel lbltitulopedir;
    private javax.swing.JLabel lbltitulotabla;
    private javax.swing.JLabel lblultserv;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JScrollPane scrollultsev;
    private javax.swing.JTable tablaclientes;
    private javax.swing.JTable tablaconducts;
    private javax.swing.JTable tablageneral;
    private javax.swing.JTable tblcantservs;
    private javax.swing.JTable tblservs_clientes;
    private javax.swing.JTable tblultserv;
    private javax.swing.JTable tblvalt_mediopago;
    private javax.swing.JTable tblvalt_servs;
    // End of variables declaration//GEN-END:variables
}
