/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author julxo
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtdirecc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtapell = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jcbgenero = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jppass = new javax.swing.JPasswordField();
        jppassconfirm = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jcbtipouser = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        txttel2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnarchfoto = new javax.swing.JButton();
        lblarchfoto = new javax.swing.JLabel();
        lblfotocond = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Usuario");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRAR USUARIO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 510, 43));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdirecc.setBackground(new java.awt.Color(51, 51, 51));
        txtdirecc.setForeground(new java.awt.Color(255, 255, 255));
        txtdirecc.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        txtdirecc.setCaretColor(new java.awt.Color(255, 255, 255));
        txtdirecc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtdirecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 159, 105, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, -1, -1));

        txtapell.setBackground(new java.awt.Color(51, 51, 51));
        txtapell.setForeground(new java.awt.Color(255, 255, 255));
        txtapell.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        txtapell.setCaretColor(new java.awt.Color(255, 255, 255));
        txtapell.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtapell, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 133, 105, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Identificación");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Genero");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, -1, -1));

        txtnom.setBackground(new java.awt.Color(51, 51, 51));
        txtnom.setForeground(new java.awt.Color(255, 255, 255));
        txtnom.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        txtnom.setCaretColor(new java.awt.Color(255, 255, 255));
        txtnom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 101, 105, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));

        txtnac.setBackground(new java.awt.Color(51, 51, 51));
        txtnac.setForeground(new java.awt.Color(255, 255, 255));
        txtnac.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        txtnac.setCaretColor(new java.awt.Color(255, 255, 255));
        txtnac.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtnac, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 284, 105, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nacionalidad");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 286, -1, -1));

        txtid.setBackground(new java.awt.Color(51, 51, 51));
        txtid.setForeground(new java.awt.Color(255, 255, 255));
        txtid.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        txtid.setCaretColor(new java.awt.Color(255, 255, 255));
        txtid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtid.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 63, 105, -1));

        jcbgenero.setBackground(new java.awt.Color(51, 51, 51));
        jcbgenero.setForeground(new java.awt.Color(255, 255, 255));
        jcbgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Especificado", "Femenino", "Masculino", "No Binario" }));
        jPanel1.add(jcbgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 250, 105, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Usuario");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Contraseña");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        txtusuario.setBackground(new java.awt.Color(51, 51, 51));
        txtusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtusuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        txtusuario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 105, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Confirmar Contraseña");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jppass.setBackground(new java.awt.Color(51, 51, 51));
        jppass.setForeground(new java.awt.Color(255, 255, 255));
        jppass.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        jppass.setCaretColor(new java.awt.Color(255, 255, 255));
        jppass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jppass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 105, -1));

        jppassconfirm.setBackground(new java.awt.Color(51, 51, 51));
        jppassconfirm.setForeground(new java.awt.Color(255, 255, 255));
        jppassconfirm.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        jppassconfirm.setCaretColor(new java.awt.Color(255, 255, 255));
        jppassconfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jppassconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 105, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de Usuario");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, -1, -1));

        jcbtipouser.setBackground(new java.awt.Color(51, 51, 51));
        jcbtipouser.setForeground(new java.awt.Color(255, 255, 255));
        jcbtipouser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Cliente" }));
        jcbtipouser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbtipouserItemStateChanged(evt);
            }
        });
        jPanel1.add(jcbtipouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 18, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefono");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 192, -1, -1));

        txttel.setBackground(new java.awt.Color(51, 51, 51));
        txttel.setForeground(new java.awt.Color(255, 255, 255));
        txttel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        txttel.setCaretColor(new java.awt.Color(255, 255, 255));
        txttel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 190, 105, -1));

        txttel2.setBackground(new java.awt.Color(51, 51, 51));
        txttel2.setForeground(new java.awt.Color(255, 255, 255));
        txttel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        txttel2.setCaretColor(new java.awt.Color(255, 255, 255));
        txttel2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txttel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 219, 105, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telefono 2 (Opcional)");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, -1, -1));

        btnarchfoto.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnarchfoto.setText("Seleccionar...");
        jPanel1.add(btnarchfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 105, -1));

        lblarchfoto.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblarchfoto.setForeground(new java.awt.Color(255, 255, 255));
        lblarchfoto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblarchfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 234, 28));

        lblfotocond.setForeground(new java.awt.Color(255, 255, 255));
        lblfotocond.setText("Foto Conductor");
        jPanel1.add(lblfotocond, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        btnregistrar.setText("Registrar");
        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 325, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 520, 10));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 54, -1, 250));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 46, 520, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbtipouserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbtipouserItemStateChanged
        if(jcbtipouser.getSelectedItem().equals("Conductor")){
            btnarchfoto.setVisible(true);
            lblfotocond.setVisible(true);
        }else{
            btnarchfoto.setVisible(false);
            lblfotocond.setVisible(false);
            lblarchfoto.setText("");
        }
    }//GEN-LAST:event_jcbtipouserItemStateChanged

    public JButton getBtnarchfoto() {
        return btnarchfoto;
    }

    public void setBtnarchfoto(JButton btnarchfoto) {
        this.btnarchfoto = btnarchfoto;
    }

    public JLabel getLblarchfoto() {
        return lblarchfoto;
    }

    public void setLblarchfoto(JLabel lblarchfoto) {
        this.lblarchfoto = lblarchfoto;
    }

    public JLabel getLblfotocond() {
        return lblfotocond;
    }

    public void setLblfotocond(JLabel lblfotocond) {
        this.lblfotocond = lblfotocond;
    }

    public JTextField getTxttel() {
        return txttel;
    }

    public void setTxttel(JTextField txttel) {
        this.txttel = txttel;
    }

    public JTextField getTxttel2() {
        return txttel2;
    }

    public void setTxttel2(JTextField txttel2) {
        this.txttel2 = txttel2;
    }

    
    public JComboBox<String> getJcbtipouser() {
        return jcbtipouser;
    }

    public void setJcbtipouser(JComboBox<String> jcbtipouser) {    
        this.jcbtipouser = jcbtipouser;
    }

    public JButton getBtnregistrar() {
        return btnregistrar;
    }

    public void setBtnregistrar(JButton btnregistrar) {
        this.btnregistrar = btnregistrar;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JComboBox<String> getJcbgenero() {
        return jcbgenero;
    }

    public void setJcbgenero(JComboBox<String> jcbgenero) {
        this.jcbgenero = jcbgenero;
    }

    public JPasswordField getJppass() {
        return jppass;
    }

    public void setJppass(JPasswordField jppass) {
        this.jppass = jppass;
    }

    public JPasswordField getJppassconfirm() {
        return jppassconfirm;
    }

    public void setJppassconfirm(JPasswordField jppassconfirm) {
        this.jppassconfirm = jppassconfirm;
    }

    public JTextField getTxtapell() {
        return txtapell;
    }

    public void setTxtapell(JTextField txtapell) {
        this.txtapell = txtapell;
    }

    public JTextField getTxtdirecc() {
        return txtdirecc;
    }

    public void setTxtdirecc(JTextField txtdirecc) {
        this.txtdirecc = txtdirecc;
    }

    public JTextField getTxtid() {
        return txtid;
    }

    public void setTxtid(JTextField txtid) {
        this.txtid = txtid;
    }

    public JTextField getTxtnac() {
        return txtnac;
    }

    public void setTxtnac(JTextField txtnac) {
        this.txtnac = txtnac;
    }

    public JTextField getTxtnom() {
        return txtnom;
    }

    public void setTxtnom(JTextField txtnom) {
        this.txtnom = txtnom;
    }

    public JTextField getTxtusuario() {
        return txtusuario;
    }

    /**
     * @param args the command line arguments
     */
    public void setTxtusuario(JTextField txtusuario) {
        this.txtusuario = txtusuario;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnarchfoto;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> jcbgenero;
    private javax.swing.JComboBox<String> jcbtipouser;
    private javax.swing.JPasswordField jppass;
    private javax.swing.JPasswordField jppassconfirm;
    private javax.swing.JLabel lblarchfoto;
    private javax.swing.JLabel lblfotocond;
    private javax.swing.JTextField txtapell;
    private javax.swing.JTextField txtdirecc;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnac;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txttel2;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
