/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;

/**
 *
 * @author julxo
 */
public class Valoracion extends javax.swing.JFrame {

    /**
     * Creates new form Valoracion
     */
    public Valoracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtn = new javax.swing.ButtonGroup();
        rbtn1 = new javax.swing.JRadioButton();
        rbtn2 = new javax.swing.JRadioButton();
        rbtn3 = new javax.swing.JRadioButton();
        rbtn4 = new javax.swing.JRadioButton();
        rbtn5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnaceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        rbtn1.setText("1");

        rbtn2.setText("2");

        rbtn3.setText("3");

        rbtn4.setText("4");

        rbtn5.setText("5");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Su último servicio a terminado con éxito, ¡puntúalo!");

        btnaceptar.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtn1)
                        .addGap(68, 68, 68)
                        .addComponent(rbtn2)
                        .addGap(82, 82, 82)
                        .addComponent(rbtn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtn4)
                        .addGap(57, 57, 57)
                        .addComponent(rbtn5)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(btnaceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn5)
                    .addComponent(rbtn4)
                    .addComponent(rbtn3)
                    .addComponent(rbtn2)
                    .addComponent(rbtn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnaceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnaceptar() {
        return btnaceptar;
    }

    public void setBtnaceptar(JButton btnaceptar) {
        this.btnaceptar = btnaceptar;
    }

    public ButtonGroup getGbtn() {
        return gbtn;
    }

    public void setGbtn(ButtonGroup gbtn) {
        this.gbtn = gbtn;
    }

    public JRadioButton getRbtn1() {
        return rbtn1;
    }

    public void setRbtn1(JRadioButton rbtn1) {
        this.rbtn1 = rbtn1;
    }

    public JRadioButton getRbtn2() {
        return rbtn2;
    }

    public void setRbtn2(JRadioButton rbtn2) {
        this.rbtn2 = rbtn2;
    }

    public JRadioButton getRbtn3() {
        return rbtn3;
    }

    public void setRbtn3(JRadioButton rbtn3) {
        this.rbtn3 = rbtn3;
    }

    public JRadioButton getRbtn4() {
        return rbtn4;
    }

    public void setRbtn4(JRadioButton rbtn4) {
        this.rbtn4 = rbtn4;
    }

    public JRadioButton getRbtn5() {
        return rbtn5;
    }

    public void setRbtn5(JRadioButton rbtn5) {
        this.rbtn5 = rbtn5;
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.ButtonGroup gbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbtn1;
    private javax.swing.JRadioButton rbtn2;
    private javax.swing.JRadioButton rbtn3;
    private javax.swing.JRadioButton rbtn4;
    private javax.swing.JRadioButton rbtn5;
    // End of variables declaration//GEN-END:variables
}
