package modelodto;
// Generated 12/05/2023 08:02:19 PM by Hibernate Tools 4.3.1



/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int idCat;
     private String nombre;
     private float tarifa;

    public Categoria() {
    }

    public Categoria(int idCat, String nombre, float tarifa) {
       this.idCat = idCat;
       this.nombre = nombre;
       this.tarifa = tarifa;
    }
   
    public int getIdCat() {
        return this.idCat;
    }
    
    public void setIdCat(int idCat) {
        this.idCat = idCat;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public float getTarifa() {
        return this.tarifa;
    }
    
    public void setTarifa(float tarifa) {
        this.tarifa = tarifa;
    }




}


