package modelodto;
// Generated 12/05/2023 08:02:19 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private long idCliente;
     private String usuario;
     private String nombre;
     private String apellido;
     private String direccion;
     private String genero;
     private String nacionalidad;

    public Cliente() {
    }

	
    public Cliente(long idCliente, String usuario, String nombre, String apellido, String direccion, String genero, String nacionalidad) {
        this.idCliente = idCliente;
        this.usuario = usuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.genero = genero;
        this.nacionalidad= nacionalidad;
    }
   
    public long getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(long idCliente) {
        this.idCliente = idCliente;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    @Override
    public String toString() {
        TelCliente tel=new TelCliente();
        return "idCliente=" + idCliente +
                "\nusuario=" + usuario +
                "\nnombre=" + nombre + "" + 
                "\napellido=" + apellido + 
                "\ndireccion=" + direccion + 
                "\ngenero=" + genero + 
                "\nnacionalidad=" + nacionalidad +
                "\ntelClientes=" + tel.toString();
    }

    



}


