package modelodto;
// Generated 12/05/2023 08:02:19 PM by Hibernate Tools 4.3.1



/**
 * RegServicio generated by hbm2java
 */
public class RegServicio  implements java.io.Serializable {


     private long id_cond;
     private long id_cliente;
     private int id_serv;
     private String medioPago;
     private String fecha;
     private int idCat;
     private int idRuta;
     private String estado;

    public RegServicio() {
    }

    public RegServicio(long id_cond, long id_cliente, int id_serv, String medioPago, String fecha, int idCat, int idRuta, String estado) {
        this.id_cond = id_cond;
        this.id_cliente = id_cliente;
        this.id_serv = id_serv;
        this.medioPago = medioPago;
        this.fecha = fecha;
        this.idCat = idCat;
        this.idRuta = idRuta;
        this.estado = estado;
    }

    public long getId_cond() {
        return id_cond;
    }

    public void setId_cond(long id_cond) {
        this.id_cond = id_cond;
    }

    public long getId_cliente() {
        return id_cliente;
    }

    public void setId_cliente(long id_cliente) {
        this.id_cliente = id_cliente;
    }

    public int getId_serv() {
        return id_serv;
    }

    public void setId_serv(int id_serv) {
        this.id_serv = id_serv;
    }

    public String getMedioPago() {
        return medioPago;
    }

    public void setMedioPago(String medioPago) {
        this.medioPago = medioPago;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public int getIdCat() {
        return idCat;
    }

    public void setIdCat(int idCat) {
        this.idCat = idCat;
    }

    public int getIdRuta() {
        return idRuta;
    }

    public void setIdRuta(int idRuta) {
        this.idRuta = idRuta;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }       
    
    @Override
    public String toString() {
        return "idcond=" + id_cond +
                "\nidcliente=" + id_cliente +
                "\nidservicio=" + id_serv +
                "\nmedioPago=" + medioPago +
                "\nfecha=" + fecha +
                "\nidCat=" + idCat +
                "\nidRuta=" + idRuta +
                "\nestado=" + estado;
    }
    



}


