package modelodto;
// Generated 12/05/2023 08:02:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private int idServ;
     private String nombre;
     private double tarifa;

    public Servicio() {
    }

    public Servicio(int idServ, String nombre, double tarifa) {
        this.idServ = idServ;
        this.nombre = nombre;
        this.tarifa = tarifa;
    }
   
    public int getIdServ() {
        return this.idServ;
    }
    
    public void setIdServ(int idServ) {
        this.idServ = idServ;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public double getTarifa() {
        return tarifa;
    }

    public void setTarifa(double tarifa) {
        this.tarifa = tarifa;
    }

}


