package modelodto;
// Generated 12/05/2023 08:02:19 PM by Hibernate Tools 4.3.1



/**
 * TelConductor generated by hbm2java
 */
public class TelConductor  implements java.io.Serializable {


     private long id_cond;
     private long telefono;

    public TelConductor() {
    }

    public TelConductor(long id_cond, long telefono) {
        this.id_cond = id_cond;
        this.telefono = telefono;
    }

    public long getId_cond() {
        return id_cond;
    }

    public void setId_cond(long id_cond) {
        this.id_cond = id_cond;
    }

    public long getTelefono() {
        return telefono;
    }

    public void setTelefono(long telefono) {
        this.telefono = telefono;
    }
       

}


