package modelodto;
// Generated 12/05/2023 08:02:19 PM by Hibernate Tools 4.3.1



/**
 * TelCliente generated by hbm2java
 */
public class TelCliente  implements java.io.Serializable {


     private long id_cliente;
     private long telefono;

    public TelCliente() {
    }

    public TelCliente(long id_cliente, long telefono) {
        this.id_cliente = id_cliente;
        this.telefono = telefono;
    }

    public long getId_cliente() {
        return id_cliente;
    }

    public void setId_cliente(long id_cliente) {
        this.id_cliente = id_cliente;
    }

    public long getTelefono() {
        return telefono;
    }

    public void setTelefono(long telefono) {
        this.telefono = telefono;
    }

    @Override
    public String toString() {
        return "id_cliente=" + id_cliente +
                "\ntelefono=" + telefono;
    }
    



}


