package modelodto;
// Generated 12/05/2023 08:02:19 PM by Hibernate Tools 4.3.1



/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String placa;
     private int modelo;
     private long idCond;
     private int idServ;

    public Vehiculo() {
    }

    public Vehiculo(String placa, int modelo, long idCond, int idServ) {
       this.placa = placa;
       this.modelo = modelo;
       this.idCond = idCond;
       this.idServ = idServ;
    }
   
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public int getModelo() {
        return this.modelo;
    }
    
    public void setModelo(int modelo) {
        this.modelo = modelo;
    }
    public long getIdCond() {
        return this.idCond;
    }
    
    public void setIdCond(long idCond) {
        this.idCond = idCond;
    }
    public int getIdServ() {
        return this.idServ;
    }
    
    public void setIdServ(int idServ) {
        this.idServ = idServ;
    }




}


